bugfix: linter changes, readme fixes

diff --git a/mvnw b/mvnw
--- a/mvnw
+++ b/mvnw
@@ -34,14 +34,14 @@
 #   MAVEN_SKIP_RC - flag to disable loading of mavenrc files
 # ----------------------------------------------------------------------------
 
-if [ -z "$MAVEN_SKIP_RC" ] ; then
+if [ -z "${MAVEN_SKIP_RC}" ] ; then
 
   if [ -f /etc/mavenrc ] ; then
     . /etc/mavenrc
   fi
 
-  if [ -f "$HOME/.mavenrc" ] ; then
-    . "$HOME/.mavenrc"
+  if [ -f "${HOME}/.mavenrc" ] ; then
+    . "${HOME}/.mavenrc"
   fi
 
 fi
@@ -50,15 +50,15 @@ fi
 cygwin=false;
 darwin=false;
 mingw=false
-case "`uname`" in
+case "$(uname)" in
   CYGWIN*) cygwin=true ;;
   MINGW*) mingw=true;;
   Darwin*) darwin=true
     # Use /usr/libexec/java_home if available, otherwise fall back to /Library/Java/Home
     # See https://developer.apple.com/library/mac/qa/qa1170/_index.html
-    if [ -z "$JAVA_HOME" ]; then
+    if [ -z "${JAVA_HOME}" ]; then
       if [ -x "/usr/libexec/java_home" ]; then
-        export JAVA_HOME="`/usr/libexec/java_home`"
+        export JAVA_HOME="$(/usr/libexec/java_home)"
       else
         export JAVA_HOME="/Library/Java/Home"
       fi
@@ -66,96 +66,96 @@ case "`uname`" in
     ;;
 esac
 
-if [ -z "$JAVA_HOME" ] ; then
+if [ -z "${JAVA_HOME}" ] ; then
   if [ -r /etc/gentoo-release ] ; then
-    JAVA_HOME=`java-config --jre-home`
+    JAVA_HOME=$(java-config --jre-home)
   fi
 fi
 
-if [ -z "$M2_HOME" ] ; then
+if [ -z "${M2_HOME}" ] ; then
   ## resolve links - $0 may be a link to maven's home
   PRG="$0"
 
   # need this for relative symlinks
-  while [ -h "$PRG" ] ; do
-    ls=`ls -ld "$PRG"`
-    link=`expr "$ls" : '.*-> \(.*\)$'`
-    if expr "$link" : '/.*' > /dev/null; then
-      PRG="$link"
+  while [ -h "${PRG}" ] ; do
+    ls=$(ls -ld "${PRG}")
+    link=$(expr "${ls}" : '.*-> \(.*\)$')
+    if expr "${link}" : '/.*' > /dev/null; then
+      PRG="${link}"
     else
-      PRG="`dirname "$PRG"`/$link"
+      PRG="$(dirname "${PRG}")/${link}"
     fi
   done
 
-  saveddir=`pwd`
+  saveddir=$(pwd)
 
-  M2_HOME=`dirname "$PRG"`/..
+  M2_HOME=$(dirname "${PRG}")/..
 
   # make it fully qualified
-  M2_HOME=`cd "$M2_HOME" && pwd`
+  M2_HOME=$(cd "${M2_HOME}" && pwd)
 
-  cd "$saveddir"
+  cd "${saveddir}" || exit
   # echo Using m2 at $M2_HOME
 fi
 
 # For Cygwin, ensure paths are in UNIX format before anything is touched
-if $cygwin ; then
-  [ -n "$M2_HOME" ] &&
-    M2_HOME=`cygpath --unix "$M2_HOME"`
-  [ -n "$JAVA_HOME" ] &&
-    JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
-  [ -n "$CLASSPATH" ] &&
-    CLASSPATH=`cygpath --path --unix "$CLASSPATH"`
+if ${cygwin} ; then
+  [ -n "${M2_HOME}" ] &&
+    M2_HOME=$(cygpath --unix "${M2_HOME}")
+  [ -n "${JAVA_HOME}" ] &&
+    JAVA_HOME=$(cygpath --unix "${JAVA_HOME}")
+  [ -n "${CLASSPATH}" ] &&
+    CLASSPATH=$(cygpath --path --unix "${CLASSPATH}")
 fi
 
 # For Mingw, ensure paths are in UNIX format before anything is touched
-if $mingw ; then
-  [ -n "$M2_HOME" ] &&
-    M2_HOME="`(cd "$M2_HOME"; pwd)`"
-  [ -n "$JAVA_HOME" ] &&
-    JAVA_HOME="`(cd "$JAVA_HOME"; pwd)`"
+if ${mingw} ; then
+  [ -n "${M2_HOME}" ] &&
+    M2_HOME="$((cd "${M2_HOME}" || exit; pwd))"
+  [ -n "${JAVA_HOME}" ] &&
+    JAVA_HOME="$((cd "${JAVA_HOME}" || exit; pwd))"
 fi
 
-if [ -z "$JAVA_HOME" ]; then
-  javaExecutable="`which javac`"
-  if [ -n "$javaExecutable" ] && ! [ "`expr \"$javaExecutable\" : '\([^ ]*\)'`" = "no" ]; then
+if [ -z "${JAVA_HOME}" ]; then
+  javaExecutable="$(which javac)"
+  if [ -n "${javaExecutable}" ] && ! [ "$(expr \${"${javaExecutabl}"}e\" : '\([^ ]*\)')" = "no" ]; then
     # readlink(1) is not available as standard on Solaris 10.
-    readLink=`which readlink`
-    if [ ! `expr "$readLink" : '\([^ ]*\)'` = "no" ]; then
-      if $darwin ; then
-        javaHome="`dirname \"$javaExecutable\"`"
-        javaExecutable="`cd \"$javaHome\" && pwd -P`/javac"
+    readLink=$(which readlink)
+    if [ ! $(expr "${readLink}" : '\([^ ]*\)') = "no" ]; then
+      if ${darwin} ; then
+        javaHome="$(dirname \${"${javaExecutabl}"}e\")"
+        javaExecutable="$(cd \${"${javaHom}"}e\" && pwd -P)/javac"
       else
-        javaExecutable="`readlink -f \"$javaExecutable\"`"
+        javaExecutable="$(readlink -f \${"${javaExecutabl}"}e\")"
       fi
-      javaHome="`dirname \"$javaExecutable\"`"
-      javaHome=`expr "$javaHome" : '\(.*\)/bin'`
-      JAVA_HOME="$javaHome"
+      javaHome="$(dirname \${"${javaExecutabl}"}e\")"
+      javaHome=$(expr "${javaHome}" : '\(.*\)/bin')
+      JAVA_HOME="${javaHome}"
       export JAVA_HOME
     fi
   fi
 fi
 
-if [ -z "$JAVACMD" ] ; then
-  if [ -n "$JAVA_HOME"  ] ; then
-    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
+if [ -z "${JAVACMD}" ] ; then
+  if [ -n "${JAVA_HOME}"  ] ; then
+    if [ -x "${JAVA_HOME}/jre/sh/java" ] ; then
       # IBM's JDK on AIX uses strange locations for the executables
-      JAVACMD="$JAVA_HOME/jre/sh/java"
+      JAVACMD="${JAVA_HOME}/jre/sh/java"
     else
-      JAVACMD="$JAVA_HOME/bin/java"
+      JAVACMD="${JAVA_HOME}/bin/java"
     fi
   else
-    JAVACMD="`which java`"
+    JAVACMD="$(which java)"
   fi
 fi
 
-if [ ! -x "$JAVACMD" ] ; then
+if [ ! -x "${JAVACMD}" ] ; then
   echo "Error: JAVA_HOME is not defined correctly." >&2
-  echo "  We cannot execute $JAVACMD" >&2
+  echo "  We cannot execute ${JAVACMD}" >&2
   exit 1
 fi
 
-if [ -z "$JAVA_HOME" ] ; then
+if [ -z "${JAVA_HOME}" ] ; then
   echo "Warning: JAVA_HOME environment variable is not set."
 fi
 
@@ -173,14 +173,14 @@ find_maven_basedir() {
 
   basedir="$1"
   wdir="$1"
-  while [ "$wdir" != '/' ] ; do
-    if [ -d "$wdir"/.mvn ] ; then
-      basedir=$wdir
+  while [ "${wdir}" != '/' ] ; do
+    if [ -d "${wdir}"/.mvn ] ; then
+      basedir=${wdir}
       break
     fi
     # workaround for JBEAP-8937 (on Solaris 10/Sparc)
     if [ -d "${wdir}" ]; then
-      wdir=`cd "$wdir/.."; pwd`
+      wdir=$(cd "${wdir}/.." || exit; pwd)
     fi
     # end of workaround
   done
@@ -194,8 +194,8 @@ concat_lines() {
   fi
 }
 
-BASE_DIR=`find_maven_basedir "$(pwd)"`
-if [ -z "$BASE_DIR" ]; then
+BASE_DIR=$(find_maven_basedir "$(pwd)")
+if [ -z "${BASE_DIR}" ]; then
   exit 1;
 fi
 
@@ -203,73 +203,73 @@ fi
 # Extension to allow automatically downloading the maven-wrapper.jar from Maven-central
 # This allows using the maven wrapper in projects that prohibit checking in binary data.
 ##########################################################################################
-if [ -r "$BASE_DIR/.mvn/wrapper/maven-wrapper.jar" ]; then
-    if [ "$MVNW_VERBOSE" = true ]; then
+if [ -r "${BASE_DIR}/.mvn/wrapper/maven-wrapper.jar" ]; then
+    if [ "${MVNW_VERBOSE}" = true ]; then
       echo "Found .mvn/wrapper/maven-wrapper.jar"
     fi
 else
-    if [ "$MVNW_VERBOSE" = true ]; then
+    if [ "${MVNW_VERBOSE}" = true ]; then
       echo "Couldn't find .mvn/wrapper/maven-wrapper.jar, downloading it ..."
     fi
-    if [ -n "$MVNW_REPOURL" ]; then
-      jarUrl="$MVNW_REPOURL/io/takari/maven-wrapper/0.5.6/maven-wrapper-0.5.6.jar"
+    if [ -n "${MVNW_REPOURL}" ]; then
+      jarUrl="${MVNW_REPOURL}/io/takari/maven-wrapper/0.5.6/maven-wrapper-0.5.6.jar"
     else
       jarUrl="https://repo.maven.apache.org/maven2/io/takari/maven-wrapper/0.5.6/maven-wrapper-0.5.6.jar"
     fi
     while IFS="=" read key value; do
-      case "$key" in (wrapperUrl) jarUrl="$value"; break ;;
+      case "${key}" in (wrapperUrl) jarUrl="${value}"; break ;;
       esac
-    done < "$BASE_DIR/.mvn/wrapper/maven-wrapper.properties"
-    if [ "$MVNW_VERBOSE" = true ]; then
-      echo "Downloading from: $jarUrl"
+    done < "${BASE_DIR}/.mvn/wrapper/maven-wrapper.properties"
+    if [ "${MVNW_VERBOSE}" = true ]; then
+      echo "Downloading from: ${jarUrl}"
     fi
-    wrapperJarPath="$BASE_DIR/.mvn/wrapper/maven-wrapper.jar"
-    if $cygwin; then
-      wrapperJarPath=`cygpath --path --windows "$wrapperJarPath"`
+    wrapperJarPath="${BASE_DIR}/.mvn/wrapper/maven-wrapper.jar"
+    if ${cygwin}; then
+      wrapperJarPath=$(cygpath --path --windows "${wrapperJarPath}")
     fi
 
     if command -v wget > /dev/null; then
-        if [ "$MVNW_VERBOSE" = true ]; then
+        if [ "${MVNW_VERBOSE}" = true ]; then
           echo "Found wget ... using wget"
         fi
-        if [ -z "$MVNW_USERNAME" ] || [ -z "$MVNW_PASSWORD" ]; then
-            wget "$jarUrl" -O "$wrapperJarPath"
+        if [ -z "${MVNW_USERNAME}" ] || [ -z "${MVNW_PASSWORD}" ]; then
+            wget "${jarUrl}" -O "${wrapperJarPath}"
         else
-            wget --http-user=$MVNW_USERNAME --http-password=$MVNW_PASSWORD "$jarUrl" -O "$wrapperJarPath"
+            wget --http-user="${MVNW_USERNAME}" --http-password="${MVNW_PASSWORD}" "${jarUrl}" -O "${wrapperJarPath}"
         fi
     elif command -v curl > /dev/null; then
-        if [ "$MVNW_VERBOSE" = true ]; then
+        if [ "${MVNW_VERBOSE}" = true ]; then
           echo "Found curl ... using curl"
         fi
-        if [ -z "$MVNW_USERNAME" ] || [ -z "$MVNW_PASSWORD" ]; then
-            curl -o "$wrapperJarPath" "$jarUrl" -f
+        if [ -z "${MVNW_USERNAME}" ] || [ -z "${MVNW_PASSWORD}" ]; then
+            curl -o "${wrapperJarPath}" "${jarUrl}" -f
         else
-            curl --user $MVNW_USERNAME:$MVNW_PASSWORD -o "$wrapperJarPath" "$jarUrl" -f
+            curl --user "${MVNW_USERNAME}":"${MVNW_PASSWORD}" -o "${wrapperJarPath}" "${jarUrl}" -f
         fi
 
     else
-        if [ "$MVNW_VERBOSE" = true ]; then
+        if [ "${MVNW_VERBOSE}" = true ]; then
           echo "Falling back to using Java to download"
         fi
-        javaClass="$BASE_DIR/.mvn/wrapper/MavenWrapperDownloader.java"
+        javaClass="${BASE_DIR}/.mvn/wrapper/MavenWrapperDownloader.java"
         # For Cygwin, switch paths to Windows format before running javac
-        if $cygwin; then
-          javaClass=`cygpath --path --windows "$javaClass"`
+        if ${cygwin}; then
+          javaClass=$(cygpath --path --windows "${javaClass}")
         fi
-        if [ -e "$javaClass" ]; then
-            if [ ! -e "$BASE_DIR/.mvn/wrapper/MavenWrapperDownloader.class" ]; then
-                if [ "$MVNW_VERBOSE" = true ]; then
+        if [ -e "${javaClass}" ]; then
+            if [ ! -e "${BASE_DIR}/.mvn/wrapper/MavenWrapperDownloader.class" ]; then
+                if [ "${MVNW_VERBOSE}" = true ]; then
                   echo " - Compiling MavenWrapperDownloader.java ..."
                 fi
                 # Compiling the Java class
-                ("$JAVA_HOME/bin/javac" "$javaClass")
+                ("${JAVA_HOME}/bin/javac" "${javaClass}")
             fi
-            if [ -e "$BASE_DIR/.mvn/wrapper/MavenWrapperDownloader.class" ]; then
+            if [ -e "${BASE_DIR}/.mvn/wrapper/MavenWrapperDownloader.class" ]; then
                 # Running the downloader
-                if [ "$MVNW_VERBOSE" = true ]; then
+                if [ "${MVNW_VERBOSE}" = true ]; then
                   echo " - Running MavenWrapperDownloader.java ..."
                 fi
-                ("$JAVA_HOME/bin/java" -cp .mvn/wrapper MavenWrapperDownloader "$MAVEN_PROJECTBASEDIR")
+                ("${JAVA_HOME}/bin/java" -cp .mvn/wrapper MavenWrapperDownloader "${MAVEN_PROJECTBASEDIR}")
             fi
         fi
     fi
@@ -278,33 +278,33 @@ fi
 # End of extension
 ##########################################################################################
 
-export MAVEN_PROJECTBASEDIR=${MAVEN_BASEDIR:-"$BASE_DIR"}
-if [ "$MVNW_VERBOSE" = true ]; then
-  echo $MAVEN_PROJECTBASEDIR
+export MAVEN_PROJECTBASEDIR="${MAVEN_BASEDIR:-"${BASE_DIR}"}"
+if [ "${MVNW_VERBOSE}" = true ]; then
+  echo "${MAVEN_PROJECTBASEDIR}"
 fi
-MAVEN_OPTS="$(concat_lines "$MAVEN_PROJECTBASEDIR/.mvn/jvm.config") $MAVEN_OPTS"
+MAVEN_OPTS="$(concat_lines "${MAVEN_PROJECTBASEDIR}/.mvn/jvm.config") ${MAVEN_OPTS}"
 
 # For Cygwin, switch paths to Windows format before running java
-if $cygwin; then
-  [ -n "$M2_HOME" ] &&
-    M2_HOME=`cygpath --path --windows "$M2_HOME"`
-  [ -n "$JAVA_HOME" ] &&
-    JAVA_HOME=`cygpath --path --windows "$JAVA_HOME"`
-  [ -n "$CLASSPATH" ] &&
-    CLASSPATH=`cygpath --path --windows "$CLASSPATH"`
-  [ -n "$MAVEN_PROJECTBASEDIR" ] &&
-    MAVEN_PROJECTBASEDIR=`cygpath --path --windows "$MAVEN_PROJECTBASEDIR"`
+if ${cygwin}; then
+  [ -n "${M2_HOME}" ] &&
+    M2_HOME=$(cygpath --path --windows "${M2_HOME}")
+  [ -n "${JAVA_HOME}" ] &&
+    JAVA_HOME=$(cygpath --path --windows "${JAVA_HOME}")
+  [ -n "${CLASSPATH}" ] &&
+    CLASSPATH=$(cygpath --path --windows "${CLASSPATH}")
+  [ -n "${MAVEN_PROJECTBASEDIR}" ] &&
+    MAVEN_PROJECTBASEDIR=$(cygpath --path --windows "${MAVEN_PROJECTBASEDIR}")
 fi
 
 # Provide a "standardized" way to retrieve the CLI args that will
 # work with both Windows and non-Windows executions.
-MAVEN_CMD_LINE_ARGS="$MAVEN_CONFIG $@"
+MAVEN_CMD_LINE_ARGS="${MAVEN_CONFIG} $@"
 export MAVEN_CMD_LINE_ARGS
 
 WRAPPER_LAUNCHER=org.apache.maven.wrapper.MavenWrapperMain
 
-exec "$JAVACMD" \
-  $MAVEN_OPTS \
-  -classpath "$MAVEN_PROJECTBASEDIR/.mvn/wrapper/maven-wrapper.jar" \
+exec "${JAVACMD}" \
+  "${MAVEN_OPTS}" \
+  -classpath "${MAVEN_PROJECTBASEDIR}/.mvn/wrapper/maven-wrapper.jar" \
   "-Dmaven.home=${M2_HOME}" "-Dmaven.multiModuleProjectDirectory=${MAVEN_PROJECTBASEDIR}" \
-  ${WRAPPER_LAUNCHER} $MAVEN_CONFIG "$@"
+  "${WRAPPER_LAUNCHER}" "${MAVEN_CONFIG}" "$@"
